### ISSUE TITLE
Follow-up work ...

### ISSUE THREAD

**Issue by Johann-bE** [proophboard/java-cody-server#3]
Follow-up work resulting from the results of generated files either generated manually or with AI: 

- Result: AI generated files are unlikely to be used. Therefore we have to do it manually.
- estimation: 0,5 - 2 days 
  * Generate code frame with the help of the swagger interface doc
  * add the "to implement" parts
  * add the other files necessary for the process 

- Kai prepares the next step. Juan takes over support for Kai and checks
- Johann: looks to get 1 more day for Kai

**Comment by kaitorched** [comment]
Only https://github.com/proophboard/java-cody-server/issues/4 remains now.
